/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'dyinanc' at '3/13/16 4:36 PM' with Gradle 2.10
 *
 * @author dyinanc, @date 3/13/16 4:36 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
